package com.warehouseproject.entity;
// Generated Dec 10, 2019 4:44:28 PM by Hibernate Tools 5.1.0.Alpha1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Inventory generated by hbm2java
 */

@Entity
@Table(name="Inventory")
public class Inventory implements java.io.Serializable {
	
    @Id
    @Column(name="invId")
	private Integer invId;
    
    @Column(name="invName")
    private String invName;
    
    @Column(name="invDescription")
	private String invDescription;
    
    @Column(name="invImage")
	private String invImage;
    
    @Column(name="invThumbnail")
	private String invThumbnail;
    
    @Column(name="invPrice")
	private BigDecimal invPrice;
    
    @Column(name="invStock")
	private short invStock;
    
    @Column(name="invSize")
	private short invSize;
    
    @Column(name="invWeight")
	private short invWeight;
    
    @Column(name="invLocation")
	private String invLocation;
    
    @Column(name="categoryId")
	private int categoryId;
    
    @Column(name="invVendor")
	private String invVendor;
    
    @Column(name="invStyle")
	private String invStyle;
    
	/*private Set reviewses = new HashSet(0);
	private Set imageses = new HashSet(0);*/

	public Inventory() {
	}

	public Inventory(String invName, String invDescription, String invImage, String invThumbnail, BigDecimal invPrice,
			short invStock, short invSize, short invWeight, String invLocation, int categoryId, String invVendor,
			String invStyle) {
		this.invName = invName;
		this.invDescription = invDescription;
		this.invImage = invImage;
		this.invThumbnail = invThumbnail;
		this.invPrice = invPrice;
		this.invStock = invStock;
		this.invSize = invSize;
		this.invWeight = invWeight;
		this.invLocation = invLocation;
		this.categoryId = categoryId;
		this.invVendor = invVendor;
		this.invStyle = invStyle;
	}

	/*public Inventory(String invName, String invDescription, String invImage, String invThumbnail, BigDecimal invPrice,
			short invStock, short invSize, short invWeight, String invLocation, int categoryId, String invVendor,
			String invStyle, Set reviewses, Set imageses) {
		this.invName = invName;
		this.invDescription = invDescription;
		this.invImage = invImage;
		this.invThumbnail = invThumbnail;
		this.invPrice = invPrice;
		this.invStock = invStock;
		this.invSize = invSize;
		this.invWeight = invWeight;
		this.invLocation = invLocation;
		this.categoryId = categoryId;
		this.invVendor = invVendor;
		this.invStyle = invStyle;
		this.reviewses = reviewses;
		this.imageses = imageses;
	}*/

	public Integer getInvId() {
		return this.invId;
	}

	public void setInvId(Integer invId) {
		this.invId = invId;
	}

	public String getInvName() {
		return this.invName;
	}

	public void setInvName(String invName) {
		this.invName = invName;
	}

	public String getInvDescription() {
		return this.invDescription;
	}

	public void setInvDescription(String invDescription) {
		this.invDescription = invDescription;
	}

	public String getInvImage() {
		return this.invImage;
	}

	public void setInvImage(String invImage) {
		this.invImage = invImage;
	}

	public String getInvThumbnail() {
		return this.invThumbnail;
	}

	public void setInvThumbnail(String invThumbnail) {
		this.invThumbnail = invThumbnail;
	}

	public BigDecimal getInvPrice() {
		return this.invPrice;
	}

	public void setInvPrice(BigDecimal invPrice) {
		this.invPrice = invPrice;
	}

	public short getInvStock() {
		return this.invStock;
	}

	public void setInvStock(short invStock) {
		this.invStock = invStock;
	}

	public short getInvSize() {
		return this.invSize;
	}

	public void setInvSize(short invSize) {
		this.invSize = invSize;
	}

	public short getInvWeight() {
		return this.invWeight;
	}

	public void setInvWeight(short invWeight) {
		this.invWeight = invWeight;
	}

	public String getInvLocation() {
		return this.invLocation;
	}

	public void setInvLocation(String invLocation) {
		this.invLocation = invLocation;
	}

	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	public String getInvVendor() {
		return this.invVendor;
	}

	public void setInvVendor(String invVendor) {
		this.invVendor = invVendor;
	}

	public String getInvStyle() {
		return this.invStyle;
	}

	public void setInvStyle(String invStyle) {
		this.invStyle = invStyle;
	}

	/*public Set getReviewses() {
		return this.reviewses;
	}

	public void setReviewses(Set reviewses) {
		this.reviewses = reviewses;
	}

	public Set getImageses() {
		return this.imageses;
	}

	public void setImageses(Set imageses) {
		this.imageses = imageses;
	}*/

}
